---
#-------------------------------------------------------------------------------------------------------------

#-------------------------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See https://go.microsoft.com/fwlink/?linkid=2090316 for license information.
version: "3.3"

secrets:
  triggers:
    file: ../sampleConfiguration/triggers.json
  mqtt:
    file: ../sampleConfiguration/mqtt.json
  telegram:
    file: ../sampleConfiguration/telegram.json

services:
  trigger:
    environment:
      - DEEPSTACK_URI=http://deepstack-ai:5000/
      - TZ=America/Los_Angeles
      - PROCESS_EXISTING_IMAGES=true
    image: node:alpine
    build:
      context: .
      dockerfile: Dockerfile # Apply development-only overrides to the base alpine image
    depends_on:
      - deepstack-ai
    volumes:
      - ..:/workspace:cached
      - ../sampleConfiguration/images:/images
    secrets:
      - triggers
      - mqtt
      - telegram

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"

  mqtt:
    image: eclipse-mosquitto:latest
    ports:
      - 1883:1883
    # For testing purposes enable basic authentication via configuration files
    # For auth testing use user and pass for the username and password
    volumes:
      - ./mosquitoMqttConfig:/mosquitto/config

  deepstack-ai:
    image: deepquestai/deepstack:latest
    volumes:
      - localstorage:/datastore
    environment:
      - VISION-DETECTION=True

volumes:
  localstorage:
